message("finding OpenSSL...")
if (UNIX)
find_library(OPENSLL_libssl NAMES libssl.a)
find_library(OPENSLL_libcrypto NAMES libcrypto.a)
find_path(OPENSSL_INCLUDE_DIR NAMES include/openssl)
find_path(OPENSSL_BIN_DIR NAMES lib/libcrypto.a)
else()
find_library(OPENSLL_libssl NAMES libssl.lib)
find_library(OPENSLL_libcrypto NAMES libcrypto.lib)
find_path(OPENSSL_INCLUDE_DIR NAMES include/openssl)
find_path(OPENSSL_BIN_DIR NAMES libcrypto-3.dll)
endif (UNIX)
message(OPENSSL_INCLUDE_DIR> ${OPENSSL_INCLUDE_DIR})
message(OPENSLL_libssl>${OPENSLL_libssl})
message(OPENSLL_libcrypto>${OPENSLL_libcrypto})
message(OPENSSL_BIN_DIR>${OPENSSL_BIN_DIR})
include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(openssl REQUIRED_VARS OPENSLL_libssl OPENSLL_libcrypto OPENSSL_INCLUDE_DIR OPENSSL_BIN_DIR)